# PSF Phantom Configuration
# Compatible with main simulation.py script

# Project paths and settings
project:
  total_activity: 358.7
  data_dir: "/home/sporter/synergistic_Y90/prepared_data/phantom_data/anthropomorphic_phantom_data/SPECT/phantom_140"
  image_path: "/home/sporter/synergistic_Y90/MIC23_STIR_SIMIND/output/psf_140/recon_osem_i5_s12_smoothed_0.hv"  # Will be updated dynamically
  output_dir: "/home/sporter/synergistic_Y90/MIC23_STIR_SIMIND/output/psf_140"
  output_prefix: "output_iter1_"  # Will be updated dynamically
  simind_parent_dir: "/home/sporter/synergistic_Y90/MIC23_STIR_SIMIND"
  axial_slice: 32

# Data file names (relative to data_dir)
data:
  mu_map_filename: "umap_zoomed.hv"
  measured_data_filename: "peak.hs"

# Simulation parameters
simulation:
  photon_multiplier: 10
  photon_energy: 150
  window_lower: 75
  window_upper: 225
  time_per_projection: 40
  source_type: "y90_frey"
  collimator: "ma-megp"
  kev_per_channel: 10
  max_energy: 2080
  scoring_routine: 1  # scattwin
  collimator_routine: 1
  photon_direction: 3
  crystal_thickness: 9.5
  crystal_half_length_radius: 195
  crystal_half_width: 265
  half_life: 64.6

# OSEM Settings (for pipeline compatibility)
osem:
  initial_subsets: 12
  initial_epochs: 5
  smoothing: true

# Pipeline Settings (for pipeline compatibility)
pipeline:
  num_iterations: 5
  num_array_jobs: 10

# Output settings (for pipeline compatibility)
output:
  base_output_dir: "/home/sporter/synergistic_Y90/MIC23_STIR_SIMIND/output"
  suffix: "psf_140"

# Sum Scatter Settings
sum_scatter:
  scatter_pattern: "*_iter%ITER%_*_sca_w1.hs"
  total_pattern: "*_iter%ITER%_*_tot_w1.hs"
  image_pattern: "recon_osem_i*_s*_smoothed_%PREV_ITER%.hv"

# Patient Processing Settings
patient_processing:
  patient_data_root: "/home/sporter/synergistic_Y90/prepared_data"
  activities_csv_filename: "activities.csv"
  spect_activity_column_index: 2