# Test Configuration
# Compatible with main simulation.py script

# Project paths and settings
project:
  total_activity: 1  # Minimal for testing
  data_dir: "/home/sporter/synergistic_Y90/prepared_data/phantom_data/nema_phantom_data/SPECT"
  image_path: "/home/sporter/synergistic_Y90/MIC23_STIR_SIMIND/output/sirt3/recon_osem_i1_s12_smoothed_0.hv"  # Will be updated dynamically
  output_dir: "/home/sporter/synergistic_Y90/MIC23_STIR_SIMIND/output/sirt3"
  output_prefix: "output_iter1_"  # Will be updated dynamically
  simind_parent_dir: "/home/sporter/synergistic_Y90/MIC23_STIR_SIMIND"
  axial_slice: 32

# Data file names (relative to data_dir)
data:
  mu_map_filename: "umap_zoomed.hv"
  measured_data_filename: "peak.hs"

# Simulation parameters (minimal for testing)
simulation:
  photon_multiplier: 1
  photon_energy: 100
  window_lower: 50
  window_upper: 150
  time_per_projection: 20
  source_type: "y90_frey"
  collimator: "g8-megp"
  kev_per_channel: 10
  max_energy: 2080
  scoring_routine: 1  # scattwin
  collimator_routine: 0
  photon_direction: 2
  crystal_thickness: 9.5
  crystal_half_length_radius: 200
  crystal_half_width: 270
  half_life: 64.6

# OSEM Settings (for pipeline compatibility)
osem:
  initial_subsets: 12
  initial_epochs: 1  # Minimal for testing
  smoothing: true

# Pipeline Settings (for pipeline compatibility)
pipeline:
  num_iterations: 1  # Minimal for testing
  num_array_jobs: 1

# Output settings (for pipeline compatibility)
output:
  base_output_dir: "/home/sporter/synergistic_Y90/MIC23_STIR_SIMIND/output"
  suffix: "sirt3"

# Sum Scatter Settings
sum_scatter:
  scatter_pattern: "*_iter%ITER%_*_sca_w1.hs"
  total_pattern: "*_iter%ITER%_*_tot_w1.hs"
  image_pattern: "recon_osem_i*_s*_smoothed_%PREV_ITER%.hv"

# Patient Processing Settings
patient_processing:
  patient_data_root: "/home/sporter/synergistic_Y90/prepared_data"
  activities_csv_filename: "activities.csv"
  spect_activity_column_index: 2